import {
  BusinessType,
  BusinessScenarioTemplate,
  AppModule,
} from "@a2order/shared";

export const DEFAULT_BUSINESS_SCENARIOS: Record<BusinessType, BusinessScenarioTemplate> = {
  // ==========================================
  // 1. TRÀ SỮA & TOPPING (BUBBLE TEA)
  // ==========================================
  BUBBLE_TEA: {
    type: "BUBBLE_TEA",
    label: "Trà Sữa / Topping",
    businessName: "Tiệm Trà Sữa Đài Loan",
    emoji: "🧋",
    tagline: "Nhiều topping, tùy chỉnh đường đá, bán ly take-away & ship",
    description: "Kịch bản tối ưu cho quán trà sữa, trà trái cây với hệ thống tùy chọn đường đá, trân châu, kem cheese và in tem nhãn dán ly.",
    suggestedModules: [
      AppModule.CORE_POS,
      AppModule.MODULE_QR_ORDER,
      AppModule.MODULE_LANDING_PAGE,
      AppModule.MODULE_ADVANCED_ANALYTICS,
    ],
    categories: [
      { id: "ts_classic", name: "Trà Sữa Truyền Thống", emoji: "🧋" },
      { id: "ts_fruit", name: "Trà Trái Cây Tươi", emoji: "🍋" },
      { id: "ts_freshmilk", name: "Sữa Tươi Đường Đen", emoji: "🥛" },
      { id: "ts_cheese", name: "Macchiato & Kem Cheese", emoji: "🧀" },
      { id: "ts_cake", name: "Bánh Ngọt Đi Kèm", emoji: "🍰" },
    ],
    defaultTables: [
      { id: "t1", name: "Bàn 01 (Cửa sổ)", capacity: 2, zone: "Tầng 1" },
      { id: "t2", name: "Bàn 02 (Sofa)", capacity: 4, zone: "Tầng 1" },
      { id: "t3", name: "Bàn 03", capacity: 4, zone: "Tầng 1" },
      { id: "t4", name: "Bàn 04 (Nhóm học)", capacity: 6, zone: "Tầng 2" },
      { id: "t5", name: "Bàn 05 (Ban công)", capacity: 2, zone: "Tầng 2" },
      { id: "t_ta", name: "Đơn Mang Về (Take-away)", capacity: 1, zone: "Quầy Thu Ngân" },
    ],
    dishes: [
      {
        id: "bt_1",
        name: "Trà Sữa Ô Long Nướng",
        category: "Trà Sữa Truyền Thống",
        price: 38000,
        costPrice: 12000,
        station: "BAR",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1558857563-b37cfb88ed08?w=500&auto=format&fit=crop&q=80",
        description: "Hương vị trà ô long đậm đà ủ lạnh, thơm béo ngậy vị sữa nướng đặc trưng",
        variants: [
          { id: "v_m", name: "Size M (500ml)", price: 38000 },
          { id: "v_l", name: "Size L (700ml)", price: 46000 },
          { id: "v_hot", name: "Uống Nóng (500ml)", price: 38000 },
        ],
        customizationGroups: [
          {
            id: "opt_sugar",
            name: "Mức Đường",
            required: true,
            maxSelect: 1,
            options: [
              { id: "s100", name: "100% Đường Chuẩn" },
              { id: "s70", name: "70% Đường" },
              { id: "s50", name: "50% Đường (Khuyên Dùng)" },
              { id: "s30", name: "30% Ít Đường" },
              { id: "s0", name: "0% Không Đường" },
            ],
          },
          {
            id: "opt_ice",
            name: "Mức Đá",
            required: true,
            maxSelect: 1,
            options: [
              { id: "i100", name: "100% Đá Chuẩn" },
              { id: "i70", name: "70% Đá" },
              { id: "i30", name: "30% Ít Đá" },
              { id: "i0", name: "Không Đá" },
            ],
          },
          {
            id: "opt_toppings",
            name: "Topping Thêm",
            required: false,
            maxSelect: 4,
            options: [
              { id: "tp_tc_den", name: "Trân Châu Đen Dẻo", priceModifier: 6000 },
              { id: "tp_tc_trang", name: "Trân Châu Trắng 3Q", priceModifier: 8000 },
              { id: "tp_pudding", name: "Pudding Trứng Mềm", priceModifier: 8000 },
              { id: "tp_kem_cheese", name: "Kem Cheese Macchiato", priceModifier: 12000 },
              { id: "tp_thach_dua", name: "Thạch Dừa Giòn", priceModifier: 6000 },
            ],
          },
        ],
      },
      {
        id: "bt_2",
        name: "Trà Đào Cam Sả Tươi",
        category: "Trà Trái Cây Tươi",
        price: 42000,
        costPrice: 14000,
        station: "BAR",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=80",
        description: "Trà đen ủ lạnh thanh mát kết hợp lát cam vàng và miếng đào giòn ngọt thơm lừng",
        variants: [
          { id: "v_m", name: "Size M", price: 42000 },
          { id: "v_l", name: "Size L (Khổng Lồ)", price: 50000 },
        ],
        customizationGroups: [
          {
            id: "opt_sugar",
            name: "Độ Ngọt",
            required: true,
            maxSelect: 1,
            options: [
              { id: "s100", name: "Ngọt Chuẩn" },
              { id: "s70", name: "Ngọt Vừa (70%)" },
              { id: "s50", name: "Ít Ngọt (50%)" },
            ],
          },
          {
            id: "opt_toppings",
            name: "Topping",
            required: false,
            maxSelect: 3,
            options: [
              { id: "tp_dao", name: "Thêm 3 Lát Đào Giòn", priceModifier: 10000 },
              { id: "tp_hat_chia", name: "Hạt Chia Organic", priceModifier: 5000 },
              { id: "tp_thach_nha_dam", name: "Thạch Nha Đam", priceModifier: 7000 },
            ],
          },
        ],
      },
      {
        id: "bt_3",
        name: "Sữa Tươi Trân Châu Đường Đen",
        category: "Sữa Tươi Đường Đen",
        price: 45000,
        costPrice: 16000,
        station: "BAR",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?w=500&auto=format&fit=crop&q=80",
        description: "Sữa tươi thanh trùng Đà Lạt hòa quyện cùng trân châu nấu đường đen organic ấm dẻo",
        variants: [
          { id: "v_m", name: "Size M (Đã có sẵn Trân Châu)", price: 45000 },
          { id: "v_l", name: "Size L (Đã có sẵn Trân Châu)", price: 55000 },
        ],
        customizationGroups: [
          {
            id: "opt_ice",
            name: "Lượng Đá",
            required: true,
            maxSelect: 1,
            options: [
              { id: "i100", name: "Đá Chuẩn" },
              { id: "i50", name: "Ít Đá" },
            ],
          },
          {
            id: "opt_toppings",
            name: "Topping Thêm",
            required: false,
            maxSelect: 2,
            options: [
              { id: "tp_kem_cheese", name: "Thêm Váng Sữa Macchiato", priceModifier: 12000 },
              { id: "tp_pudding", name: "Thêm Pudding Trứng", priceModifier: 8000 },
            ],
          },
        ],
      },
      {
        id: "bt_4",
        name: "Bánh Tiramisu Truyền Thống",
        category: "Bánh Ngọt Đi Kèm",
        price: 35000,
        costPrice: 15000,
        station: "DESSERT",
        isAvailable: true,
        image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&auto=format&fit=crop&q=80",
        description: "Bánh mềm thơm hương rượu cà phê và lớp kem mascarpone béo ngậy chuẩn Ý",
      },
    ],
  },

  // ==========================================
  // 2. CÀ PHÊ & ĐỒ UỐNG (COFFEE SHOP)
  // ==========================================
  COFFEE_SHOP: {
    type: "COFFEE_SHOP",
    label: "Quán Cà Phê",
    businessName: "A2 Roastery Coffee",
    emoji: "☕",
    tagline: "Không gian trải nghiệm, cà phê pha máy/phin, khách trung thành",
    description: "Kịch bản hoàn hảo cho quán cà phê không gian làm việc hoặc cà phê mang đi, tích hợp in bill quầy bar và quản lý công thức đồ uống.",
    suggestedModules: [
      AppModule.CORE_POS,
      AppModule.MODULE_QR_ORDER,
      AppModule.MODULE_LANDING_PAGE,
      AppModule.MODULE_ADVANCED_ANALYTICS,
    ],
    categories: [
      { id: "cf_traditional", name: "Cà Phê Truyền Thống", emoji: "☕" },
      { id: "cf_espresso", name: "Cà Phê Ý / Máy", emoji: "🥛" },
      { id: "cf_coldbrew", name: "Cold Brew Ủ Lạnh", emoji: "🧊" },
      { id: "cf_tea", name: "Trà & Thảo Mộc", emoji: "🍃" },
      { id: "cf_bakery", name: "Bánh Nướng / Croissant", emoji: "🥐" },
    ],
    defaultTables: [
      { id: "t1", name: "Bàn 01 (Bàn tròn gỗ)", capacity: 2, zone: "Tầng 1" },
      { id: "t2", name: "Bàn 02 (Bàn làm việc dài)", capacity: 8, zone: "Tầng 1" },
      { id: "t3", name: "Bàn 03 (Sofa đôi)", capacity: 2, zone: "Tầng 1" },
      { id: "t4", name: "Bàn 04 (Góc sách)", capacity: 4, zone: "Tầng 2" },
      { id: "t5", name: "Bàn 05 (Bàn ban công view)", capacity: 2, zone: "Tầng 2" },
    ],
    dishes: [
      {
        id: "cf_1",
        name: "Cà Phê Muối Xứ Huế",
        category: "Cà Phê Truyền Thống",
        price: 32000,
        costPrice: 9500,
        station: "BAR",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80",
        description: "Cốt cà phê Robusta pha phin đậm đà kết hợp lớp kem sữa muối mặn béo ngậy hài hòa",
        variants: [
          { id: "v_std", name: "Tiêu Chuẩn (Đá)", price: 32000 },
          { id: "v_big", name: "Cỡ Lớn (Nhiều Cà Phê)", price: 42000 },
          { id: "v_hot", name: "Uống Ấm", price: 32000 },
        ],
        customizationGroups: [
          {
            id: "opt_sweet",
            name: "Độ Ngọt",
            required: true,
            maxSelect: 1,
            options: [
              { id: "sw_std", name: "Vị Chuẩn Của Quán" },
              { id: "sw_less", name: "Ít Sữa Đặc" },
            ],
          },
          {
            id: "opt_extra",
            name: "Tùy Chọn Thêm",
            required: false,
            maxSelect: 2,
            options: [
              { id: "ex_cream", name: "Thêm 1 Lớp Kem Muối", priceModifier: 10000 },
              { id: "ex_shot", name: "Thêm Shot Cà Phê Đậm", priceModifier: 10000 },
            ],
          },
        ],
      },
      {
        id: "cf_2",
        name: "Bạc Xỉu 3 Tầng Sài Gòn",
        category: "Cà Phê Truyền Thống",
        price: 29000,
        costPrice: 8500,
        station: "BAR",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=500&auto=format&fit=crop&q=80",
        description: "Hòa quyện tinh tế giữa sữa đặc ngọt bùi, sữa tươi thanh mát và lớp bọt cà phê thơm lừng",
        variants: [
          { id: "v_cold", name: "Ly Đá Sảng Khoái", price: 29000 },
          { id: "v_hot", name: "Ly Nóng Ấm Lòng", price: 29000 },
        ],
      },
      {
        id: "cf_3",
        name: "Cold Brew Cam Vàng",
        category: "Cold Brew Ủ Lạnh",
        price: 45000,
        costPrice: 15000,
        station: "BAR",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=500&auto=format&fit=crop&q=80",
        description: "Cà phê Arabica Cầu Đất ủ lạnh 18 tiếng, mix lát cam vàng Mỹ ngọt thanh giàu năng lượng",
        variants: [
          { id: "v_glass", name: "Thưởng Thức Tại Quán (Ly Thủy Tinh)", price: 45000 },
          { id: "v_bottle", name: "Đóng Chai Thủy Tinh Mang Về (250ml)", price: 55000 },
        ],
      },
      {
        id: "cf_4",
        name: "Bánh Croissant Bơ Tỏi Pháp",
        category: "Bánh Nướng / Croissant",
        price: 28000,
        costPrice: 11000,
        station: "DESSERT",
        isAvailable: true,
        image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=500&auto=format&fit=crop&q=80",
        description: "Vỏ ngàn lớp giòn rụm thơm nức mùi bơ New Zealand kết hợp xốt bơ tỏi lá mùi tây",
      },
    ],
  },

  // ==========================================
  // 3. MÌ CAY & LẨU HÀN QUỐC (SPICY NOODLE)
  // ==========================================
  SPICY_NOODLE: {
    type: "SPICY_NOODLE",
    label: "Mì Cay / Bún / Phở",
    businessName: "Mì Cay Seoul 7 Cấp Độ",
    emoji: "🍜",
    tagline: "Phân luồng màn hình bếp KDS, chọn cấp độ cay, món ăn vặt Hàn Quốc",
    description: "Kịch bản chuyên biệt cho mô hình Mì cay 7 cấp độ và món Hàn với cơ chế chọn cấp độ cay bắt buộc gửi chuẩn xác sang màn hình KDS nhà bếp.",
    suggestedModules: [
      AppModule.CORE_POS,
      AppModule.MODULE_KDS,
      AppModule.MODULE_QR_ORDER,
      AppModule.MODULE_ADVANCED_ANALYTICS,
    ],
    categories: [
      { id: "sn_spicy", name: "Mì Cay 7 Cấp Độ", emoji: "🌶️" },
      { id: "sn_hotpot", name: "Lẩu Mini 1 Người", emoji: "🍲" },
      { id: "sn_snack", name: "Ăn Vặt Hàn Quốc", emoji: "🥟" },
      { id: "sn_drink", name: "Nước Giải Cay", emoji: "🧃" },
    ],
    defaultTables: [
      { id: "t1", name: "Bàn 01", capacity: 4, zone: "Khu Trong Nhà" },
      { id: "t2", name: "Bàn 02", capacity: 4, zone: "Khu Trong Nhà" },
      { id: "t3", name: "Bàn 03", capacity: 4, zone: "Khu Trong Nhà" },
      { id: "t4", name: "Bàn 04 (Bàn Lớn)", capacity: 8, zone: "Khu Trong Nhà" },
      { id: "t5", name: "Bàn 05 (Bàn Lớn)", capacity: 8, zone: "Khu Máy Lạnh" },
    ],
    dishes: [
      {
        id: "sn_1",
        name: "Mì Cay Hải Sản Kim Chi",
        category: "Mì Cay 7 Cấp Độ",
        price: 55000,
        costPrice: 22000,
        station: "KITCHEN",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&auto=format&fit=crop&q=80",
        description: "Tôm sú tươi, mực giòn, chả cá Hàn Quốc, nấm kim châm nấu cùng nước súp kim chi đậm đà cay nồng",
        variants: [
          { id: "v_std", name: "Tô Tiêu Chuẩn", price: 55000 },
          { id: "v_special", name: "Tô Đặc Biệt (Gấp Đôi Tôm & Mực)", price: 75000 },
        ],
        customizationGroups: [
          {
            id: "opt_spicy_level",
            name: "Cấp Độ Cay (Bắt Buộc)",
            required: true,
            maxSelect: 1,
            options: [
              { id: "lv0", name: "Cấp 0 (Không Cay - Cho Trẻ Em)" },
              { id: "lv05", name: "Cấp 0.5 (Cay Lăn Tăn)" },
              { id: "lv1", name: "Cấp 1 (Cay Nhẹ Chuẩn Vị)" },
              { id: "lv2", name: "Cấp 2 (Cay Vừa Ăn - Phổ Biến)" },
              { id: "lv3", name: "Cấp 3 (Cay Nồng Đổ Mồ Hôi)" },
              { id: "lv4", name: "Cấp 4 (Cay Khô Môi)" },
              { id: "lv5", name: "Cấp 5 (Thách Thức Cực Độ)" },
              { id: "lv7", name: "Cấp 7 (Tử Thần - Ký Giấy Miễn Trừ)" },
            ],
          },
          {
            id: "opt_addons",
            name: "Món Thêm Vào Tô",
            required: false,
            maxSelect: 4,
            options: [
              { id: "ad_cheese", name: "Phô Mai Kéo Sợi Mozzarella", priceModifier: 15000 },
              { id: "ad_sausage", name: "Xúc Xích Đức Nướng", priceModifier: 10000 },
              { id: "ad_noodle", name: "Thêm Vắt Mì Ramen Hàn", priceModifier: 10000 },
              { id: "ad_beef", name: "Thêm Ba Chỉ Bò Mỹ (80g)", priceModifier: 20000 },
            ],
          },
        ],
      },
      {
        id: "sn_2",
        name: "Mì Cay Bò Mỹ Nấm Kim Châm",
        category: "Mì Cay 7 Cấp Độ",
        price: 52000,
        costPrice: 20000,
        station: "KITCHEN",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1552611052-33e04de081de?w=500&auto=format&fit=crop&q=80",
        description: "Thịt ba chỉ bò Mỹ cuộn nấm kim châm mềm ngọt ngập trong nước dùng chua cay kích thích",
        variants: [
          { id: "v_std", name: "Tô Tiêu Chuẩn", price: 52000 },
          { id: "v_big", name: "Tô Siêu Thịt Bò", price: 69000 },
        ],
        customizationGroups: [
          {
            id: "opt_spicy_level",
            name: "Cấp Độ Cay (Bắt Buộc)",
            required: true,
            maxSelect: 1,
            options: [
              { id: "lv0", name: "Cấp 0 (Không Cay)" },
              { id: "lv1", name: "Cấp 1 (Cay Dịu)" },
              { id: "lv2", name: "Cấp 2 (Vừa Ăn)" },
              { id: "lv3", name: "Cấp 3 (Cay Nhiều)" },
              { id: "lv5", name: "Cấp 5 (Siêu Cay)" },
            ],
          },
        ],
      },
      {
        id: "sn_3",
        name: "Tokbokki Lắc Phô Mai Chiên Giòn",
        category: "Ăn Vặt Hàn Quốc",
        price: 35000,
        costPrice: 12000,
        station: "KITCHEN",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1583032015879-bf6b5536585d?w=500&auto=format&fit=crop&q=80",
        description: "Bánh gạo mềm dẻo chiên vàng lớp vỏ ngoài rồi phủ lớp bột phô mai béo mặn gây nghiện",
      },
    ],
  },

  // ==========================================
  // 4. NHÀ HÀNG & CƠM GIA ĐÌNH (RESTAURANT)
  // ==========================================
  RESTAURANT: {
    type: "RESTAURANT",
    label: "Nhà Hàng Lớn",
    businessName: "Nhà Hàng Ẩm Thực Việt",
    emoji: "🍽️",
    tagline: "Phục vụ tại bàn, đặt trước phòng VIP, thực đơn món mặn gia đình",
    description: "Kịch bản vận hành đầy đủ cho nhà hàng quy mô lớn: quản lý phòng VIP, đặt bàn trước từ website, chia trạm Bếp Nấu & Bếp Nướng riêng biệt.",
    suggestedModules: [
      AppModule.CORE_POS,
      AppModule.MODULE_KDS,
      AppModule.MODULE_QR_ORDER,
      AppModule.MODULE_ADVANCED_ANALYTICS,
      AppModule.MODULE_LANDING_PAGE,
      AppModule.MODULE_ACCOUNTING,
    ],
    categories: [
      { id: "res_appetizer", name: "Món Khai Vị & Gỏi", emoji: "🥗" },
      { id: "res_main", name: "Món Chính & Đậm Đà", emoji: "🥩" },
      { id: "res_seafood", name: "Hải Sản Tươi Sống", emoji: "🦐" },
      { id: "res_hotpot", name: "Lẩu Gia Đình 4-6 Người", emoji: "🍲" },
      { id: "res_rice", name: "Cơm & Canh Truyền Thống", emoji: "🍚" },
    ],
    defaultTables: [
      { id: "t1", name: "Bàn VIP 01 (Phòng Hoàng Gia)", capacity: 12, zone: "Khu Phòng VIP" },
      { id: "t2", name: "Bàn VIP 02 (Phòng Sen)", capacity: 8, zone: "Khu Phòng VIP" },
      { id: "t3", name: "Bàn Sảnh A1", capacity: 4, zone: "Sảnh Trệt" },
      { id: "t4", name: "Bàn Sảnh A2", capacity: 4, zone: "Sảnh Trệt" },
      { id: "t5", name: "Bàn Sân Vườn B1", capacity: 6, zone: "Sân Vườn Sinh Thái" },
    ],
    dishes: [
      {
        id: "res_1",
        name: "Cơm Tấm Sườn Bì Chả Đặc Biệt",
        category: "Cơm & Canh Truyền Thống",
        price: 65000,
        costPrice: 24000,
        station: "KITCHEN",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500&auto=format&fit=crop&q=80",
        description: "Cốt sườn heo nướng than hoa mật ong thơm lừng ăn kèm bì giòn, chả trứng hấp béo bùi và mỡ hành",
        variants: [
          { id: "v_std", name: "Đĩa Tiêu Chuẩn (1 Miếng Sườn)", price: 65000 },
          { id: "v_double", name: "Đĩa Khổng Lồ (2 Cốt Sườn Nướng)", price: 95000 },
        ],
        customizationGroups: [
          {
            id: "opt_egg",
            name: "Trứng Ốp La",
            required: false,
            maxSelect: 1,
            options: [
              { id: "egg_runny", name: "Trứng Ốp La Lòng Đào", priceModifier: 8000 },
              { id: "egg_done", name: "Trứng Ốp La Chín Kỹ", priceModifier: 8000 },
            ],
          },
          {
            id: "opt_extra_side",
            name: "Món Ăn Kèm Thêm",
            required: false,
            maxSelect: 3,
            options: [
              { id: "side_rice", name: "Thêm Chén Cơm Tấm", priceModifier: 8000 },
              { id: "side_cha", name: "Thêm 1 Miếng Chả Trứng Hấp", priceModifier: 12000 },
              { id: "side_canh", name: "Thêm Tô Canh Khổ Qua Nhồi Thịt", priceModifier: 20000 },
            ],
          },
        ],
      },
      {
        id: "res_2",
        name: "Bò Lúc Lắc Khoai Tây Chiên",
        category: "Món Chính & Đậm Đà",
        price: 135000,
        costPrice: 58000,
        station: "KITCHEN",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=500&auto=format&fit=crop&q=80",
        description: "Thăn bò Úc thái quân cờ xào tiêu đen thơm lừng trên chảo gang cùng ớt chuông và khoai tây giòn",
      },
      {
        id: "res_3",
        name: "Lẩu Thái Hải Sản Tomyum (4 Người)",
        category: "Lẩu Gia Đình 4-6 Người",
        price: 320000,
        costPrice: 135000,
        station: "KITCHEN",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1547496502-affa22d38842?w=500&auto=format&fit=crop&q=80",
        description: "Nước cốt dừa thơm béo, lá chanh chúc cay nồng kèm đĩa tôm sú, mực nang, ngao và rau nấm tươi",
        variants: [
          { id: "v_pot_m", name: "Nồi Vừa (2-3 Người)", price: 250000 },
          { id: "v_pot_l", name: "Nồi Lớn (4-6 Người Ăn No)", price: 350000 },
        ],
      },
    ],
  },

  // ==========================================
  // 5. QUÁN NHẬU & BIA HƠI (BEER GARDEN)
  // ==========================================
  BEER_GARDEN: {
    type: "BEER_GARDEN",
    label: "Quán Nhậu / Bia Hơi",
    businessName: "Quán Bia Hơi Góc Phố",
    emoji: "🍺",
    tagline: "Gọi món cực nhanh, ca/tháp bia, vòng quay bàn cao",
    description: "Kịch bản tối ưu tốc độ gọi món bằng mã QR hoặc máy tính bảng phục vụ, tính tiền linh hoạt theo két/tháp bia và đĩa mồi nhắm.",
    suggestedModules: [
      AppModule.CORE_POS,
      AppModule.MODULE_KDS,
      AppModule.MODULE_QR_ORDER,
    ],
    categories: [
      { id: "bg_beer", name: "Bia Hơi & Bia Lon", emoji: "🍻" },
      { id: "bg_snack", name: "Mồi Nhắm Khô Nhanh", emoji: "🥜" },
      { id: "bg_meat", name: "Món Nướng & Chiên Xào", emoji: "🥩" },
      { id: "bg_hotpot", name: "Lẩu Nhậu Lai Rai", emoji: "🍲" },
    ],
    defaultTables: [
      { id: "t1", name: "Bàn 01 (Sân ngoài)", capacity: 6, zone: "Khu Vỉa Hè" },
      { id: "t2", name: "Bàn 02 (Sân ngoài)", capacity: 6, zone: "Khu Vỉa Hè" },
      { id: "t3", name: "Bàn 03", capacity: 8, zone: "Sảnh Sân Vườn" },
      { id: "t4", name: "Bàn 04 (Bàn Nhậu Lớn)", capacity: 12, zone: "Sảnh Sân Vườn" },
      { id: "t5", name: "Bàn 05 (Bàn Nhậu Lớn)", capacity: 12, zone: "Sảnh Sân Vườn" },
    ],
    dishes: [
      {
        id: "bg_1",
        name: "Bia Hơi Hà Nội Thượng Hạng",
        category: "Bia Hơi & Bia Lon",
        price: 15000,
        costPrice: 6000,
        station: "BAR",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1608270124698-8ec156487e83?w=500&auto=format&fit=crop&q=80",
        description: "Bia hơi tươi rói ủ lạnh xuất xưởng trong ngày, bọt trắng mịn mát lạnh sảng khoái",
        variants: [
          { id: "v_glass", name: "Cốc Thủy Tinh (330ml)", price: 15000 },
          { id: "v_pitcher", name: "Ca Rót 1.5 Lít", price: 65000 },
          { id: "v_tower", name: "Tháp Bia Có Ống Đá (3 Lít)", price: 125000 },
        ],
      },
      {
        id: "bg_2",
        name: "Khô Mực Nướng Than Hoa",
        category: "Mồi Nhắm Khô Nhanh",
        price: 110000,
        costPrice: 65000,
        station: "KITCHEN",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=500&auto=format&fit=crop&q=80",
        description: "Mực câu Cô Tô dày mình nướng than hoa đập tơi xốp chấm tương ớt cay nồng nhậu tốn bia",
        variants: [
          { id: "v_m", name: "Con Vừa (150g)", price: 110000 },
          { id: "v_l", name: "Con Lớn Thượng Hạng (250g)", price: 175000 },
        ],
      },
      {
        id: "bg_3",
        name: "Lẩu Riêu Cua Bắp Bò Sườn Sụn",
        category: "Lẩu Nhậu Lai Rai",
        price: 280000,
        costPrice: 115000,
        station: "KITCHEN",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1547496502-affa22d38842?w=500&auto=format&fit=crop&q=80",
        description: "Nước lẩu giấm bỗng chua thanh, gạch cua xịn thơm lừng, thịt bắp bò hoa và sườn sụn giòn sần sật",
        variants: [
          { id: "v_pot_m", name: "Nồi 3-4 Người", price: 280000 },
          { id: "v_pot_l", name: "Nồi 5-6 Người Ăn No", price: 380000 },
        ],
      },
    ],
  },

  // ==========================================
  // 6. ĂN VẶT & TRÀ CHANH (SNACK SHOP)
  // ==========================================
  SNACK_SHOP: {
    type: "SNACK_SHOP",
    label: "Quán Ăn Vặt",
    businessName: "Tiệm Ăn Vặt & Trà Chanh Teen",
    emoji: "🧆",
    tagline: "Phục vụ nhanh gọn, giá sinh viên, combo ăn vặt nhiều món",
    description: "Kịch bản tối ưu chi phí cho mô hình trà chanh vỉa hè và đồ ăn vặt sinh viên, menu ngắn gọn và thao tác bán hàng siêu tốc.",
    suggestedModules: [
      AppModule.CORE_POS,
      AppModule.MODULE_QR_ORDER,
    ],
    categories: [
      { id: "sk_drink", name: "Trà Chanh & Nước Ngọt", emoji: "🍋" },
      { id: "sk_fried", name: "Chiên Rán Giòn Rụm", emoji: "🍟" },
      { id: "sk_cake", name: "Bánh Tráng & Cuốn", emoji: "🌯" },
    ],
    defaultTables: [
      { id: "t1", name: "Bàn Nhựa 01", capacity: 4, zone: "Vỉa Hè" },
      { id: "t2", name: "Bàn Nhựa 02", capacity: 4, zone: "Vỉa Hè" },
      { id: "t3", name: "Bàn Nhựa 03", capacity: 4, zone: "Vỉa Hè" },
      { id: "t4", name: "Bàn Nhựa 04", capacity: 4, zone: "Trong Nhà" },
    ],
    dishes: [
      {
        id: "sk_1",
        name: "Trà Chanh Giã Tay Quảng Đông",
        category: "Trà Chanh & Nước Ngọt",
        price: 25000,
        costPrice: 7000,
        station: "BAR",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=80",
        description: "Chanh thơm được giã tay giải phóng tinh dầu thơm mát kết hợp trà xanh hoa nhài ủ lạnh",
        variants: [
          { id: "v_m", name: "Cốc Nhỏ (500ml)", price: 25000 },
          { id: "v_l", name: "Cốc Khổng Lồ (1 Lít)", price: 35000 },
        ],
      },
      {
        id: "sk_2",
        name: "Bánh Tráng Nướng Đà Lạt Trứng Cút",
        category: "Bánh Tráng & Cuốn",
        price: 25000,
        costPrice: 9000,
        station: "KITCHEN",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=500&auto=format&fit=crop&q=80",
        description: "Bánh tráng nướng giòn tan với trứng cút, hành phi thơm nức, bò khô và xốt mayonnaise cay",
      },
      {
        id: "sk_3",
        name: "Mẹt Ăn Vặt Tổng Hợp (5 Món)",
        category: "Chiên Rán Giòn Rụm",
        price: 69000,
        costPrice: 28000,
        station: "KITCHEN",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&auto=format&fit=crop&q=80",
        description: "Gồm nem chua rán, khoai tây lắc phô mai, cá viên chiên mắm, hồ lô nướng và phô mai que",
      },
    ],
  },

  // ==========================================
  // 7. NƯỚC ÉP & HEALTHY (JUICE BAR)
  // ==========================================
  JUICE_BAR: {
    type: "JUICE_BAR",
    label: "Nước Ép / Sinh Tố",
    businessName: "Green Life Juice & Detox",
    emoji: "🥤",
    tagline: "Nguyên chất 100%, không đường, sinh tố bơ dừa & sữa chua hạt",
    description: "Kịch bản cho chuỗi nước ép hoa quả nguyên chất và thực dưỡng healthy, cho phép khách chọn mức ngọt tự nhiên hoặc mật ong.",
    suggestedModules: [
      AppModule.CORE_POS,
      AppModule.MODULE_QR_ORDER,
    ],
    categories: [
      { id: "jb_detox", name: "Nước Ép Rau Củ Detox", emoji: "🥬" },
      { id: "jb_pure", name: "Nước Ép Trái Cây Tươi", emoji: "🍊" },
      { id: "jb_smoothie", name: "Sinh Tố Healthy / Granola", emoji: "🥑" },
    ],
    defaultTables: [
      { id: "t1", name: "Bàn 01", capacity: 2, zone: "Khu Quầy Bar" },
      { id: "t2", name: "Bàn 02", capacity: 4, zone: "Khu Quầy Bar" },
      { id: "t_ta", name: "Đơn Mua Mang Về", capacity: 1, zone: "Cửa Hàng" },
    ],
    dishes: [
      {
        id: "jb_1",
        name: "Nước Ép Detox Táo Cần Tây Dưa Leo",
        category: "Nước Ép Rau Củ Detox",
        price: 45000,
        costPrice: 16000,
        station: "BAR",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=80",
        description: "100% nguyên chất ép lạnh chậm giữ trọn vẹn vitamin và enzym, thanh lọc cơ thể giảm mỡ",
        variants: [
          { id: "v_cup", name: "Ly Giấy 350ml", price: 45000 },
          { id: "v_bottle", name: "Chai Thủy Tinh 500ml", price: 60000 },
        ],
        customizationGroups: [
          {
            id: "opt_sweetener",
            name: "Lựa Chọn Độ Ngọt",
            required: true,
            maxSelect: 1,
            options: [
              { id: "sw_none", name: "100% Nguyên Chất Không Thêm Ngọt" },
              { id: "sw_honey", name: "Thêm Mật Ong Rừng Tự Nhiên", priceModifier: 5000 },
            ],
          },
        ],
      },
      {
        id: "jb_2",
        name: "Sinh Tố Bơ Sáp Dừa Non",
        category: "Sinh Tố Healthy / Granola",
        price: 48000,
        costPrice: 19000,
        station: "BAR",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1553530666-ba11a7da3888?w=500&auto=format&fit=crop&q=80",
        description: "Bơ sáp Đắk Lắk dẻo quánh xay cùng cơm dừa non béo ngậy và sữa tươi nguyên kem",
      },
    ],
  },

  // ==========================================
  // 8. MÔ HÌNH ĐA DẠNG KHÁC (OTHER)
  // ==========================================
  OTHER: {
    type: "OTHER",
    label: "Loại Hình Khác",
    businessName: "Quán Ăn Hương Vị Truyền Thống",
    emoji: "🏪",
    tagline: "Phở bò, bún bò Huế, bánh mì kẹp thịt và đồ ăn sáng",
    description: "Kịch bản tổng hợp kinh điển thích hợp cho tiệm ăn sáng, quán phở, bún gia truyền với danh sách món thân quen nhất.",
    suggestedModules: [
      AppModule.CORE_POS,
    ],
    categories: [
      { id: "ot_pho", name: "Phở Bò Truyền Thống", emoji: "🍜" },
      { id: "ot_bun", name: "Bún & Bánh Mì", emoji: "🥖" },
      { id: "ot_drink", name: "Đồ Uống Giải Khát", emoji: "☕" },
    ],
    defaultTables: [
      { id: "t1", name: "Bàn 01", capacity: 4, zone: "Tầng 1" },
      { id: "t2", name: "Bàn 02", capacity: 4, zone: "Tầng 1" },
      { id: "t3", name: "Bàn 03", capacity: 4, zone: "Tầng 1" },
      { id: "t4", name: "Bàn 04", capacity: 6, zone: "Tầng 1" },
      { id: "t5", name: "Bàn 05", capacity: 6, zone: "Tầng 1" },
    ],
    dishes: [
      {
        id: "ot_1",
        name: "Phở Bò Tái Nạm Hà Nội",
        category: "Phở Bò Truyền Thống",
        price: 65000,
        costPrice: 26000,
        station: "KITCHEN",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?q=80&w=400&auto=format&fit=crop",
        description: "Thịt bò tái tươi mọng kết hợp nạm giòn thơm ngon đậm đà cùng nước dùng ninh xương 12 tiếng",
        variants: [
          { id: "v_reg", name: "Tô Thường", price: 65000 },
          { id: "v_special", name: "Tô Đặc Biệt Siêu Thịt", price: 85000 },
        ],
        customizationGroups: [
          {
            id: "opt_topping",
            name: "Món Ăn Kèm",
            required: false,
            maxSelect: 3,
            options: [
              { id: "tp_quay", name: "Đĩa Quẩy Giòn (3 Chiếc)", priceModifier: 10000 },
              { id: "tp_trung", name: "Chén Trứng Trần Nước Béo", priceModifier: 12000 },
              { id: "tp_banh_pho", name: "Thêm Bánh Phở", priceModifier: 10000 },
            ],
          },
        ],
      },
      {
        id: "ot_2",
        name: "Bánh Mì Thịt Nướng Xá Xíu",
        category: "Bún & Bánh Mì",
        price: 30000,
        costPrice: 11000,
        station: "KITCHEN",
        isAvailable: true,
        isBestSeller: true,
        image: "https://images.unsplash.com/photo-1509722747041-616f39b57569?q=80&w=400&auto=format&fit=crop",
        description: "Bánh mì nướng than nóng giòn kẹp thịt xá xíu đậm đà, pate gan béo ngậy và dưa góp chua ngọt",
      },
    ],
  },
};
