import React from "react";
import {
  LayoutGrid,
  ChefHat,
  Receipt,
  UtensilsCrossed,
  ShoppingCart,
  QrCode,
  Printer,
  Check,
  AlertTriangle,
  Trash2,
  Clock,
  Users,
  Plus,
  Minus,
  LogOut,
  Search,
  Lock,
  RotateCw,
  Globe,
  Activity,
  KeyRound,
  FileText,
  ShieldCheck,
  Building2,
  Store,
  TrendingUp,
  Flame,
  CreditCard,
  Sparkles,
  ExternalLink,
  Save,
  Monitor,
  Smartphone,
  Eye,
  Calendar,
  Filter,
  Download,
  Settings,
  HelpCircle,
  Info,
  Banknote,
  ArrowRight,
  Phone,
  X,
  Percent,
  Tag,
  DollarSign,
  Edit2,
  Wifi,
  Server,
  UserCheck,
  History,
  Ban,
  CheckCircle2,
  ClipboardList,
  CalendarCheck,
  Power,
  Mail,
  Bell,
  ArrowUpRight,
  BarChart3,
  Loader2,
  Send,
  Delete,
  AlertCircle,
  Menu as MenuBars,
  MoreHorizontal,
  LucideIcon,
} from "lucide-react";
import { IconProps, IconName } from "@/types";

const iconMap: Record<IconName, LucideIcon> = {
  table: LayoutGrid,
  kitchen: ChefHat,
  cashier: Receipt,
  menu: UtensilsCrossed,
  cart: ShoppingCart,
  vietqr: QrCode,
  print: Printer,
  check: Check,
  alert: AlertTriangle,
  trash: Trash2,
  clock: Clock,
  users: Users,
  plus: Plus,
  minus: Minus,
  logout: LogOut,
  search: Search,
  lock: Lock,
  refresh: RotateCw,
  globe: Globe,
  activity: Activity,
  key: KeyRound,
  fileText: FileText,
  shield: ShieldCheck,
  building: Building2,
  store: Store,
  trending: TrendingUp,
  flame: Flame,
  creditCard: CreditCard,
  sparkles: Sparkles,
  externalLink: ExternalLink,
  save: Save,
  monitor: Monitor,
  smartphone: Smartphone,
  eye: Eye,
  calendar: Calendar,
  filter: Filter,
  download: Download,
  settings: Settings,
  help: HelpCircle,
  info: Info,
  banknote: Banknote,
  arrowRight: ArrowRight,
  phone: Phone,
  x: X,
  percent: Percent,
  tag: Tag,
  dollar: DollarSign,
  edit: Edit2,
  wifi: Wifi,
  server: Server,
  userCheck: UserCheck,
  history: History,
  ban: Ban,
  checkCircle: CheckCircle2,
  clipboard: ClipboardList,
  calendarCheck: CalendarCheck,
  power: Power,
  mail: Mail,
  bell: Bell,
  arrowUpRight: ArrowUpRight,
  chart: BarChart3,
  loader: Loader2,
  send: Send,
  backspace: Delete,
  alertCircle: AlertCircle,
  bars: MenuBars,
  moreHorizontal: MoreHorizontal,
};

export const Icon: React.FC<IconProps> = ({ name, className = "w-5 h-5", size = 20 }) => {
  const Component = iconMap[name] || AlertTriangle;
  return <Component className={className} size={size} strokeWidth={2} />;
};
