import {
  TenantStoreRecord,
  SoftwareInvoiceRecord,
  SystemAuditLogRecord,
  AppModule,
} from "@/types/cms.types";

export interface LicenseKeyRecord {
  id: string;
  keyCode: string;
  storeName?: string;
  storeId?: string;
  plan: "STARTER" | "GROWTH" | "PRO" | "ENTERPRISE";
  maxDevices: number;
  durationMonths: number;
  issuedAt: string;
  expiresAt: string;
  status: "ACTIVE" | "EXPIRING_SOON" | "EXPIRED" | "REVOKED" | "UNASSIGNED";
  modules: AppModule[];
}

// Bộ dữ liệu mẫu vận hành chuẩn SaaS F&B toàn quốc (Hà Nội, TP.HCM, Đà Nẵng, Cần Thơ, Hải Phòng)
export const INITIAL_STORES: TenantStoreRecord[] = [
  {
    id: "s1",
    name: "Phở Bò Nam Định - Chi nhánh 1",
    owner: "Nguyễn Thành An",
    ownerEmail: "an.phobo@gmail.com",
    phone: "0912 345 678",
    address: "128 Phố Huế, Hai Bà Trưng, Hà Nội",
    tableCount: 18,
    licenseKey: "A2-PRO-9F8A2B",
    plan: "PRO",
    status: "ACTIVE",
    activatedAt: "01/09/2026",
    expiresAt: "01/10/2026",
    daysLeft: 28,
    pingMs: 12,
    activeDevices: 4,
    configVer: "v1.0.3",
    businessType: "SPICY_NOODLE",
    lastSync: "1 phút trước",
    modules: [
      AppModule.CORE_POS,
      AppModule.MODULE_KDS,
      AppModule.MODULE_QR_ORDER,
      AppModule.MODULE_LANDING_PAGE,
      AppModule.MODULE_ADVANCED_ANALYTICS,
    ],
    terminals: [
      { id: "term-101", name: "POS Thu Ngân - Quầy Chính", role: "POS_CASHIER", ipAddress: "192.168.1.101", appVersion: "v1.0.3", lastSync: "Vừa xong", status: "ONLINE" },
      { id: "term-102", name: "Màn Hình Bếp KDS", role: "KITCHEN_KDS", ipAddress: "192.168.1.102", appVersion: "v1.0.3", lastSync: "1 phút trước", status: "ONLINE" },
      { id: "term-103", name: "Màn Hình Pha Chế", role: "BAR_KDS", ipAddress: "192.168.1.103", appVersion: "v1.0.3", lastSync: "2 phút trước", status: "ONLINE" },
      { id: "term-104", name: "Tablet Phục Vụ Tầng 2", role: "TABLET_WAITER", ipAddress: "192.168.1.108", appVersion: "v1.0.3", lastSync: "3 phút trước", status: "ONLINE" },
    ],
  },
  {
    id: "s2",
    name: "Cà Phê Muối Chú Long",
    owner: "Lê Văn Hùng",
    ownerEmail: "hung.chulong@gmail.com",
    phone: "0905 999 888",
    address: "88 Trần Phú, Ba Đình, Hà Nội",
    tableCount: 12,
    licenseKey: "A2-GROWTH-31AA0",
    plan: "GROWTH",
    status: "EXPIRING_SOON",
    activatedAt: "30/08/2026",
    expiresAt: "05/10/2026",
    daysLeft: 4,
    pingMs: 22,
    activeDevices: 3,
    configVer: "v1.0.0",
    businessType: "COFFEE_SHOP",
    lastSync: "2 phút trước",
    modules: [AppModule.CORE_POS, AppModule.MODULE_QR_ORDER, AppModule.MODULE_KDS],
    terminals: [
      { id: "term-301", name: "POS Thu Ngân Quầy Bar", role: "POS_CASHIER", ipAddress: "192.168.2.10", appVersion: "v1.0.0", lastSync: "2 phút trước", status: "ONLINE" },
      { id: "term-302", name: "KDS Màn Hình Pha Chế", role: "BAR_KDS", ipAddress: "192.168.2.11", appVersion: "v1.0.0", lastSync: "3 phút trước", status: "ONLINE" },
      { id: "term-303", name: "Tablet Phục Vụ Sân Vườn", role: "TABLET_WAITER", ipAddress: "192.168.2.14", appVersion: "v1.0.0", lastSync: "12 phút trước", status: "ONLINE" },
    ],
  },
  {
    id: "s3",
    name: "Trà Sữa Topping Đô Đô",
    owner: "Phạm Hoàng Yến",
    ownerEmail: "yen.dodo@gmail.com",
    phone: "0977 888 999",
    address: "245 Sư Vạn Hạnh, Quận 10, TP. Hồ Chí Minh",
    tableCount: 22,
    licenseKey: "A2-ENT-7788AA",
    plan: "ENTERPRISE",
    status: "ACTIVE",
    activatedAt: "10/05/2026",
    expiresAt: "10/05/2027",
    daysLeft: 220,
    pingMs: 14,
    activeDevices: 8,
    configVer: "v1.1.0",
    businessType: "BUBBLE_TEA",
    lastSync: "Vừa xong",
    modules: [
      AppModule.CORE_POS,
      AppModule.MODULE_KDS,
      AppModule.MODULE_QR_ORDER,
      AppModule.MODULE_LANDING_PAGE,
      AppModule.MODULE_ADVANCED_ANALYTICS,
    ],
    terminals: [
      { id: "term-501", name: "POS Quầy 01 (Order)", role: "POS_CASHIER", ipAddress: "192.168.3.10", appVersion: "v1.1.0", lastSync: "Vừa xong", status: "ONLINE" },
      { id: "term-502", name: "POS Quầy 02 (Order)", role: "POS_CASHIER", ipAddress: "192.168.3.11", appVersion: "v1.1.0", lastSync: "Vừa xong", status: "ONLINE" },
      { id: "term-503", name: "KDS Trạm Trà & Topping", role: "BAR_KDS", ipAddress: "192.168.3.20", appVersion: "v1.1.0", lastSync: "1 phút trước", status: "ONLINE" },
      { id: "term-504", name: "KDS Trạm Đóng Nắp & Tem", role: "BAR_KDS", ipAddress: "192.168.3.21", appVersion: "v1.1.0", lastSync: "1 phút trước", status: "ONLINE" },
    ],
  },
  {
    id: "s4",
    name: "Bún Chả Cầu Giấy (Quán Nhỏ)",
    owner: "Trần Thị Mai",
    ownerEmail: "mai.buncha@gmail.com",
    phone: "0988 123 456",
    address: "45 Dịch Vọng Hậu, Cầu Giấy, Hà Nội",
    tableCount: 8,
    licenseKey: "A2-STARTER-77X1A",
    plan: "STARTER",
    status: "ACTIVE",
    activatedAt: "15/09/2026",
    expiresAt: "15/10/2026",
    daysLeft: 14,
    pingMs: 16,
    activeDevices: 2,
    configVer: "v1.0.1",
    businessType: "SNACK_SHOP",
    lastSync: "4 phút trước",
    modules: [AppModule.CORE_POS, AppModule.MODULE_QR_ORDER],
    terminals: [
      { id: "term-201", name: "POS Thu Ngân Bán Hàng", role: "POS_CASHIER", ipAddress: "192.168.0.12", appVersion: "v1.0.1", lastSync: "4 phút trước", status: "ONLINE" },
      { id: "term-202", name: "Tablet Phục Vụ 01", role: "TABLET_WAITER", ipAddress: "192.168.0.15", appVersion: "v1.0.1", lastSync: "6 phút trước", status: "ONLINE" },
    ],
  },
  {
    id: "s5",
    name: "Lẩu Nướng Phố Cổ",
    owner: "Vũ Hải Đăng",
    ownerEmail: "dang.launuong@gmail.com",
    phone: "0934 555 777",
    address: "12 Hàng Buồm, Hoàn Kiếm, Hà Nội",
    tableCount: 25,
    licenseKey: "A2-PRO-EXPIRED",
    plan: "PRO",
    status: "EXPIRED",
    activatedAt: "10/08/2026",
    expiresAt: "10/09/2026",
    daysLeft: 0,
    pingMs: 0,
    activeDevices: 0,
    configVer: "v1.0.5",
    businessType: "BEER_GARDEN",
    lastSync: "19 ngày trước",
    modules: [
      AppModule.CORE_POS,
      AppModule.MODULE_KDS,
      AppModule.MODULE_ADVANCED_ANALYTICS,
      AppModule.MODULE_LANDING_PAGE,
    ],
    terminals: [
      { id: "term-401", name: "POS Thu Ngân Chính", role: "POS_CASHIER", ipAddress: "192.168.10.5", appVersion: "v1.0.5", lastSync: "19 ngày trước", status: "OFFLINE" },
    ],
  },
  {
    id: "s6",
    name: "Tiệm Cơm Tấm Ba Ghiền",
    owner: "Trương Vĩnh Ký",
    ownerEmail: "ky.baghien@gmail.com",
    phone: "0903 111 222",
    address: "84 Đặng Văn Ngữ, Phú Nhuận, TP. Hồ Chí Minh",
    tableCount: 16,
    licenseKey: "A2-PRO-66B88C",
    plan: "PRO",
    status: "EXPIRING_SOON",
    activatedAt: "08/09/2026",
    expiresAt: "08/10/2026",
    daysLeft: 7,
    pingMs: 15,
    activeDevices: 4,
    configVer: "v1.0.4",
    businessType: "SNACK_SHOP",
    lastSync: "5 phút trước",
    modules: [AppModule.CORE_POS, AppModule.MODULE_KDS, AppModule.MODULE_QR_ORDER],
    terminals: [
      { id: "term-601", name: "POS Quầy Thu Ngân", role: "POS_CASHIER", ipAddress: "192.168.4.10", appVersion: "v1.0.4", lastSync: "5 phút trước", status: "ONLINE" },
      { id: "term-602", name: "KDS Trạm Bếp Nướng Sườn", role: "KITCHEN_KDS", ipAddress: "192.168.4.11", appVersion: "v1.0.4", lastSync: "5 phút trước", status: "ONLINE" },
    ],
  },
  {
    id: "s7",
    name: "Hải Sản Biển Đông - Sông Hàn",
    owner: "Đặng Quốc Hưng",
    ownerEmail: "hung.biendong@gmail.com",
    phone: "0918 333 444",
    address: "15 Bạch Đằng, Hải Châu, Đà Nẵng",
    tableCount: 30,
    licenseKey: "A2-ENT-8899FF",
    plan: "ENTERPRISE",
    status: "ACTIVE",
    activatedAt: "01/06/2026",
    expiresAt: "01/06/2027",
    daysLeft: 243,
    pingMs: 18,
    activeDevices: 7,
    configVer: "v1.0.8",
    businessType: "RESTAURANT",
    lastSync: "3 phút trước",
    modules: [
      AppModule.CORE_POS,
      AppModule.MODULE_KDS,
      AppModule.MODULE_QR_ORDER,
      AppModule.MODULE_ADVANCED_ANALYTICS,
    ],
    terminals: [
      { id: "term-701", name: "POS Lễ Tân Thu Ngân", role: "POS_CASHIER", ipAddress: "192.168.5.10", appVersion: "v1.0.8", lastSync: "3 phút trước", status: "ONLINE" },
      { id: "term-702", name: "KDS Trạm Hấp Nướng", role: "KITCHEN_KDS", ipAddress: "192.168.5.20", appVersion: "v1.0.8", lastSync: "3 phút trước", status: "ONLINE" },
      { id: "term-703", name: "KDS Trạm Gỏi Khai Vị", role: "KITCHEN_KDS", ipAddress: "192.168.5.21", appVersion: "v1.0.8", lastSync: "3 phút trước", status: "ONLINE" },
    ],
  },
  {
    id: "s8",
    name: "Bánh Mì Huỳnh Hoa Sài Gòn",
    owner: "Nguyễn Thị Ngọc",
    ownerEmail: "ngoc.huynhhoa@gmail.com",
    phone: "0938 777 666",
    address: "26 Lê Thị Riêng, Bến Thành, Quận 1, TP. Hồ Chí Minh",
    tableCount: 6,
    licenseKey: "A2-PRO-2233DD",
    plan: "PRO",
    status: "ACTIVE",
    activatedAt: "20/07/2026",
    expiresAt: "20/01/2027",
    daysLeft: 111,
    pingMs: 11,
    activeDevices: 3,
    configVer: "v1.0.2",
    businessType: "SNACK_SHOP",
    lastSync: "Vừa xong",
    modules: [AppModule.CORE_POS, AppModule.MODULE_QR_ORDER, AppModule.MODULE_KDS],
    terminals: [
      { id: "term-801", name: "POS Bán Hàng Mang Về", role: "POS_CASHIER", ipAddress: "192.168.6.10", appVersion: "v1.0.2", lastSync: "Vừa xong", status: "ONLINE" },
      { id: "term-802", name: "KDS Quầy Kẹp Thịt Chả", role: "KITCHEN_KDS", ipAddress: "192.168.6.12", appVersion: "v1.0.2", lastSync: "Vừa xong", status: "ONLINE" },
    ],
  },
  {
    id: "s9",
    name: "Nhà Hàng Cơm Niêu Singapore",
    owner: "Huỳnh Minh Trí",
    ownerEmail: "tri.comnieu@gmail.com",
    phone: "0944 888 111",
    address: "102 Đại Lộ Hòa Bình, Ninh Kiều, Cần Thơ",
    tableCount: 20,
    licenseKey: "A2-GROWTH-5566EE",
    plan: "GROWTH",
    status: "ACTIVE",
    activatedAt: "12/08/2026",
    expiresAt: "12/02/2027",
    daysLeft: 134,
    pingMs: 25,
    activeDevices: 4,
    configVer: "v1.0.3",
    businessType: "RESTAURANT",
    lastSync: "8 phút trước",
    modules: [AppModule.CORE_POS, AppModule.MODULE_KDS, AppModule.MODULE_QR_ORDER],
    terminals: [
      { id: "term-901", name: "POS Quầy Lễ Tân", role: "POS_CASHIER", ipAddress: "192.168.7.10", appVersion: "v1.0.3", lastSync: "8 phút trước", status: "ONLINE" },
    ],
  },
  {
    id: "s10",
    name: "The Coffee House - Lạch Tray",
    owner: "Võ Tấn Lộc",
    ownerEmail: "loc.tch@gmail.com",
    phone: "0972 555 999",
    address: "68 Lạch Tray, Ngô Quyền, Hải Phòng",
    tableCount: 28,
    licenseKey: "A2-ENT-9911CC",
    plan: "ENTERPRISE",
    status: "ACTIVE",
    activatedAt: "05/04/2026",
    expiresAt: "05/04/2027",
    daysLeft: 186,
    pingMs: 14,
    activeDevices: 6,
    configVer: "v1.1.2",
    businessType: "COFFEE_SHOP",
    lastSync: "1 phút trước",
    modules: [
      AppModule.CORE_POS,
      AppModule.MODULE_KDS,
      AppModule.MODULE_QR_ORDER,
      AppModule.MODULE_LANDING_PAGE,
      AppModule.MODULE_ADVANCED_ANALYTICS,
    ],
    terminals: [
      { id: "term-1001", name: "POS Quầy Order 1", role: "POS_CASHIER", ipAddress: "192.168.8.10", appVersion: "v1.1.2", lastSync: "1 phút trước", status: "ONLINE" },
      { id: "term-1002", name: "POS Quầy Order 2", role: "POS_CASHIER", ipAddress: "192.168.8.11", appVersion: "v1.1.2", lastSync: "1 phút trước", status: "ONLINE" },
      { id: "term-1003", name: "KDS Trạm Pha Chế Bar", role: "BAR_KDS", ipAddress: "192.168.8.20", appVersion: "v1.1.2", lastSync: "1 phút trước", status: "ONLINE" },
    ],
  },
];

export const INITIAL_LICENSES: LicenseKeyRecord[] = [
  {
    id: "lic-1",
    keyCode: "A2-ENT-7788AA",
    storeName: "Trà Sữa Topping Đô Đô",
    storeId: "s3",
    plan: "ENTERPRISE",
    maxDevices: 10,
    durationMonths: 12,
    issuedAt: "10/05/2026",
    expiresAt: "10/05/2027",
    status: "ACTIVE",
    modules: [AppModule.CORE_POS, AppModule.MODULE_KDS, AppModule.MODULE_QR_ORDER, AppModule.MODULE_LANDING_PAGE, AppModule.MODULE_ADVANCED_ANALYTICS],
  },
  {
    id: "lic-2",
    keyCode: "A2-PRO-9F8A2B",
    storeName: "Phở Bò Nam Định - Chi nhánh 1",
    storeId: "s1",
    plan: "PRO",
    maxDevices: 5,
    durationMonths: 6,
    issuedAt: "01/09/2026",
    expiresAt: "01/10/2026",
    status: "ACTIVE",
    modules: [AppModule.CORE_POS, AppModule.MODULE_KDS, AppModule.MODULE_QR_ORDER, AppModule.MODULE_LANDING_PAGE],
  },
  {
    id: "lic-3",
    keyCode: "A2-GROWTH-31AA0",
    storeName: "Cà Phê Muối Chú Long",
    storeId: "s2",
    plan: "GROWTH",
    maxDevices: 3,
    durationMonths: 3,
    issuedAt: "30/08/2026",
    expiresAt: "05/10/2026",
    status: "EXPIRING_SOON",
    modules: [AppModule.CORE_POS, AppModule.MODULE_KDS, AppModule.MODULE_QR_ORDER],
  },
  {
    id: "lic-4",
    keyCode: "A2-PRO-EXPIRED",
    storeName: "Lẩu Nướng Phố Cổ",
    storeId: "s5",
    plan: "PRO",
    maxDevices: 6,
    durationMonths: 1,
    issuedAt: "10/08/2026",
    expiresAt: "10/09/2026",
    status: "EXPIRED",
    modules: [AppModule.CORE_POS, AppModule.MODULE_KDS],
  },
  {
    id: "lic-5",
    keyCode: "A2-STARTER-77X1A",
    storeName: "Bún Chả Cầu Giấy (Quán Nhỏ)",
    storeId: "s4",
    plan: "STARTER",
    maxDevices: 2,
    durationMonths: 12,
    issuedAt: "15/09/2026",
    expiresAt: "15/10/2026",
    status: "ACTIVE",
    modules: [AppModule.CORE_POS, AppModule.MODULE_QR_ORDER],
  },
  {
    id: "lic-6",
    keyCode: "A2-PRO-66B88C",
    storeName: "Tiệm Cơm Tấm Ba Ghiền",
    storeId: "s6",
    plan: "PRO",
    maxDevices: 5,
    durationMonths: 6,
    issuedAt: "08/09/2026",
    expiresAt: "08/10/2026",
    status: "EXPIRING_SOON",
    modules: [AppModule.CORE_POS, AppModule.MODULE_KDS, AppModule.MODULE_QR_ORDER],
  },
  {
    id: "lic-7",
    keyCode: "A2-ENT-8899FF",
    storeName: "Hải Sản Biển Đông - Sông Hàn",
    storeId: "s7",
    plan: "ENTERPRISE",
    maxDevices: 12,
    durationMonths: 12,
    issuedAt: "01/06/2026",
    expiresAt: "01/06/2027",
    status: "ACTIVE",
    modules: [AppModule.CORE_POS, AppModule.MODULE_KDS, AppModule.MODULE_QR_ORDER, AppModule.MODULE_ADVANCED_ANALYTICS],
  },
  {
    id: "lic-8",
    keyCode: "A2-KEY-STANDBY-01",
    plan: "PRO",
    maxDevices: 5,
    durationMonths: 6,
    issuedAt: "28/09/2026",
    expiresAt: "28/03/2027",
    status: "UNASSIGNED",
    modules: [AppModule.CORE_POS, AppModule.MODULE_KDS, AppModule.MODULE_QR_ORDER],
  },
];

export const INITIAL_INVOICES: SoftwareInvoiceRecord[] = [
  {
    id: "inv-1",
    invoiceCode: "INV-2026-0091",
    storeId: "s3",
    storeName: "Trà Sữa Topping Đô Đô",
    plan: "Gói Chuỗi Doanh Nghiệp (ENTERPRISE)",
    durationMonths: 12,
    subTotal: 15588000,
    discountAmount: 2588000,
    finalAmount: 13000000,
    status: "PAID",
    paymentMethod: "VIETQR",
    createdAt: "10/05/2026",
    paidAt: "10/05/2026 09:15",
  },
  {
    id: "inv-2",
    invoiceCode: "INV-2026-0092",
    storeId: "s1",
    storeName: "Phở Bò Nam Định - Chi nhánh 1",
    plan: "Gói Chuỗi Chuyên Nghiệp (PRO)",
    durationMonths: 6,
    subTotal: 3594000,
    discountAmount: 600000,
    finalAmount: 2994000,
    status: "PAID",
    paymentMethod: "VIETQR",
    createdAt: "01/09/2026",
    paidAt: "01/09/2026 14:30",
  },
  {
    id: "inv-3",
    invoiceCode: "INV-2026-0093",
    storeId: "s2",
    storeName: "Cà Phê Muối Chú Long",
    plan: "Gói Quán Tăng Trưởng (GROWTH)",
    durationMonths: 3,
    subTotal: 1197000,
    discountAmount: 100000,
    finalAmount: 1097000,
    status: "PENDING",
    paymentMethod: "VIETQR",
    createdAt: "28/09/2026",
  },
  {
    id: "inv-4",
    invoiceCode: "INV-2026-0094",
    storeId: "s6",
    storeName: "Tiệm Cơm Tấm Ba Ghiền",
    plan: "Gói Chuỗi Chuyên Nghiệp (PRO)",
    durationMonths: 6,
    subTotal: 3594000,
    discountAmount: 300000,
    finalAmount: 3294000,
    status: "PENDING",
    paymentMethod: "VIETQR",
    createdAt: "30/09/2026",
  },
  {
    id: "inv-5",
    invoiceCode: "INV-2026-0095",
    storeId: "s4",
    storeName: "Bún Chả Cầu Giấy (Quán Nhỏ)",
    plan: "Gói Quán Nhỏ Tiết Kiệm (STARTER)",
    durationMonths: 12,
    subTotal: 2388000,
    discountAmount: 400000,
    finalAmount: 1988000,
    status: "PAID",
    paymentMethod: "VIETQR",
    createdAt: "15/09/2026",
    paidAt: "15/09/2026 10:15",
  },
  {
    id: "inv-6",
    invoiceCode: "INV-2026-0096",
    storeId: "s7",
    storeName: "Hải Sản Biển Đông - Sông Hàn",
    plan: "Gói Chuỗi Doanh Nghiệp (ENTERPRISE)",
    durationMonths: 12,
    subTotal: 15588000,
    discountAmount: 2000000,
    finalAmount: 13588000,
    status: "PAID",
    paymentMethod: "VIETQR",
    createdAt: "01/06/2026",
    paidAt: "01/06/2026 11:20",
  },
];

export const INITIAL_AUDIT_LOGS: SystemAuditLogRecord[] = [
  {
    id: "a1",
    action: "EXTEND_LICENSE",
    storeName: "Trà Sữa Topping Đô Đô",
    actor: "superadmin@a2order.vn",
    actorRole: "SUPER_ADMIN",
    ipAddress: "14.225.24.12",
    timestamp: "18:45 Hôm nay",
    details: "Kích hoạt gia hạn hợp đồng thuê 12 tháng. Cập nhật License Key A2-ENT-7788AA",
    status: "SUCCESS",
  },
  {
    id: "a2",
    action: "CONFIRM_INVOICE",
    storeName: "Phở Bò Nam Định",
    actor: "superadmin@a2order.vn",
    actorRole: "SUPER_ADMIN",
    ipAddress: "14.225.24.12",
    timestamp: "15:20 Hôm nay",
    details: "Xác nhận đối soát 2.994.000đ qua VietQR. Nâng cấp 4 trạm POS/KDS",
    status: "SUCCESS",
  },
  {
    id: "a3",
    action: "POS_SYNC",
    storeName: "Hải Sản Biển Đông - Sông Hàn",
    actor: "pos.gateway@a2order.internal",
    actorRole: "SYSTEM",
    ipAddress: "192.168.5.10",
    timestamp: "14:05 Hôm nay",
    details: "Đồng bộ snapshot thực đơn v1.0.8 thành công tới 7 trạm máy trạm",
    status: "SUCCESS",
  },
  {
    id: "a4",
    action: "AUTH_LOGIN",
    storeName: "Nền tảng A2Order HQ",
    actor: "superadmin@a2order.vn",
    actorRole: "SUPER_ADMIN",
    ipAddress: "14.225.24.12",
    timestamp: "12:00 Hôm nay",
    details: "Đăng nhập Super Admin bảo mật 2 lớp qua phiên làm việc HTTPS",
    status: "SUCCESS",
  },
  {
    id: "a5",
    action: "CONFIG_CHANGE",
    storeName: "The Coffee House - Lạch Tray",
    actor: "loc.tch@gmail.com",
    actorRole: "STORE_OWNER",
    ipAddress: "118.70.182.4",
    timestamp: "11:30 Hôm nay",
    details: "Chủ quán xuất bản cấu hình phân vùng sơ đồ bàn v1.1.2",
    status: "SUCCESS",
  },
  {
    id: "a6",
    action: "CREATE_KEY",
    storeName: "Kho License Nền Tảng",
    actor: "superadmin@a2order.vn",
    actorRole: "SUPER_ADMIN",
    ipAddress: "14.225.24.12",
    timestamp: "09:15 Hôm nay",
    details: "Sinh mới mã khóa bản quyền dự phòng A2-KEY-STANDBY-01 (Gói PRO 6 tháng)",
    status: "SUCCESS",
  },
  {
    id: "a7",
    action: "WARNING_OFFLINE",
    storeName: "Lẩu Nướng Phố Cổ",
    actor: "heartbeat.monitor@a2order.internal",
    actorRole: "SYSTEM",
    ipAddress: "192.168.10.5",
    timestamp: "Hôm qua 23:50",
    details: "Hợp đồng thuê hết hạn. Hệ thống tạm khóa đồng bộ dữ liệu trạm POS",
    status: "WARNING",
  },
  {
    id: "a8",
    action: "INVOICE_CREATE",
    storeName: "Tiệm Cơm Tấm Ba Ghiền",
    actor: "billing.worker@a2order.internal",
    actorRole: "SYSTEM",
    ipAddress: "10.0.0.1",
    timestamp: "Hôm qua 16:30",
    details: "Tự động phát hành hóa đơn gia hạn INV-2026-0094 trước 7 ngày hết hạn",
    status: "SUCCESS",
  },
];
