import {
  TenantStoreRecord,
  SoftwareInvoiceRecord,
  SystemAuditLogRecord,
  AppModule,
} from "@/types/cms.types";

export interface LicenseKeyRecord {
  id: string;
  keyCode: string;
  storeName?: string;
  storeId?: string;
  plan: "STARTER" | "GROWTH" | "PRO" | "ENTERPRISE";
  maxDevices: number;
  durationMonths: number;
  issuedAt: string;
  expiresAt: string;
  status: "ACTIVE" | "EXPIRING_SOON" | "EXPIRED" | "REVOKED" | "UNASSIGNED";
  modules: AppModule[];
}

export const INITIAL_LICENSES: LicenseKeyRecord[] = [
  {
    id: "lic-1",
    keyCode: "A2-PRO-9F8A2B",
    storeName: "Phở Bò Nam Định - Chi nhánh 1",
    storeId: "s1",
    plan: "PRO",
    maxDevices: 4,
    durationMonths: 1,
    issuedAt: "01/09/2026",
    expiresAt: "01/10/2026",
    status: "ACTIVE",
    modules: [
      AppModule.CORE_POS,
      AppModule.MODULE_KDS,
      AppModule.MODULE_QR_ORDER,
      AppModule.MODULE_ADVANCED_ANALYTICS,
      AppModule.MODULE_LANDING_PAGE,
    ],
  },
  {
    id: "lic-2",
    keyCode: "A2-STARTER-77X1A",
    storeName: "Bún Chả Cầu Giấy (Quán Nhỏ)",
    storeId: "s2",
    plan: "STARTER",
    maxDevices: 2,
    durationMonths: 1,
    issuedAt: "15/09/2026",
    expiresAt: "15/10/2026",
    status: "ACTIVE",
    modules: [AppModule.CORE_POS, AppModule.MODULE_QR_ORDER],
  },
  {
    id: "lic-3",
    keyCode: "A2-GROWTH-31AA0",
    storeName: "Cà Phê Muối Chú Long",
    storeId: "s3",
    plan: "GROWTH",
    maxDevices: 3,
    durationMonths: 1,
    issuedAt: "30/08/2026",
    expiresAt: "30/09/2026",
    status: "EXPIRING_SOON",
    modules: [AppModule.CORE_POS, AppModule.MODULE_KDS, AppModule.MODULE_QR_ORDER],
  },
  {
    id: "lic-4",
    keyCode: "A2-PRO-88BCC2",
    storeName: "Quán Ốc Sài Gòn Đêm",
    storeId: "s4",
    plan: "PRO",
    maxDevices: 5,
    durationMonths: 1,
    issuedAt: "01/08/2026",
    expiresAt: "01/09/2026",
    status: "EXPIRED",
    modules: [AppModule.CORE_POS, AppModule.MODULE_KDS, AppModule.MODULE_QR_ORDER],
  },
  {
    id: "lic-5",
    keyCode: "A2-GROWTH-99KEY1",
    plan: "GROWTH",
    maxDevices: 3,
    durationMonths: 6,
    issuedAt: "20/09/2026",
    expiresAt: "20/03/2027",
    status: "UNASSIGNED",
    modules: [AppModule.CORE_POS, AppModule.MODULE_KDS, AppModule.MODULE_QR_ORDER],
  },
];

export const INITIAL_STORES: TenantStoreRecord[] = [
  {
    id: "s1",
    name: "Phở Bò Nam Định - Chi nhánh 1",
    owner: "Nguyễn Thành An",
    phone: "0912 345 678",
    address: "128 Phố Huế, Hai Bà Trưng, Hà Nội",
    tableCount: 18,
    licenseKey: "A2-PRO-9F8A2B",
    plan: "PRO",
    status: "ACTIVE",
    activatedAt: "01/09/2026",
    expiresAt: "01/10/2026",
    daysLeft: 28,
    pingMs: 12,
    activeDevices: 4,
    configVer: "v1.0.3",
    businessType: "SPICY_NOODLE",
    lastSync: "1 phút trước",
    modules: [
      AppModule.CORE_POS,
      AppModule.MODULE_KDS,
      AppModule.MODULE_QR_ORDER,
      AppModule.MODULE_LANDING_PAGE,
      AppModule.MODULE_ADVANCED_ANALYTICS,
    ],
    terminals: [
      { id: "term-101", name: "POS Thu Ngân - Quầy Chính", role: "POS_CASHIER", ipAddress: "192.168.1.101", appVersion: "v1.0.3", lastSync: "Vừa xong", status: "ONLINE" },
      { id: "term-102", name: "Màn Hình Bếp KDS", role: "KITCHEN_KDS", ipAddress: "192.168.1.102", appVersion: "v1.0.3", lastSync: "1 phút trước", status: "ONLINE" },
      { id: "term-103", name: "Màn Hình Pha Chế", role: "BAR_KDS", ipAddress: "192.168.1.103", appVersion: "v1.0.3", lastSync: "2 phút trước", status: "ONLINE" },
      { id: "term-104", name: "Tablet Phục Vụ Tầng 2", role: "TABLET_WAITER", ipAddress: "192.168.1.108", appVersion: "v1.0.3", lastSync: "3 phút trước", status: "ONLINE" },
    ],
  },
  {
    id: "s2",
    name: "Bún Chả Cầu Giấy (Quán Nhỏ)",
    owner: "Trần Thị Mai",
    phone: "0988 123 456",
    address: "45 Dịch Vọng Hậu, Cầu Giấy, Hà Nội",
    tableCount: 8,
    licenseKey: "A2-STARTER-77X1A",
    plan: "STARTER",
    status: "ACTIVE",
    activatedAt: "15/09/2026",
    expiresAt: "15/10/2026",
    daysLeft: 14,
    pingMs: 16,
    activeDevices: 2,
    configVer: "v1.0.1",
    businessType: "SNACK_SHOP",
    lastSync: "4 phút trước",
    modules: [AppModule.CORE_POS, AppModule.MODULE_QR_ORDER],
    terminals: [
      { id: "term-201", name: "POS Thu Ngân Bán Hàng", role: "POS_CASHIER", ipAddress: "192.168.0.12", appVersion: "v1.0.1", lastSync: "4 phút trước", status: "ONLINE" },
      { id: "term-202", name: "Tablet Phục Vụ 01", role: "TABLET_WAITER", ipAddress: "192.168.0.15", appVersion: "v1.0.1", lastSync: "6 phút trước", status: "ONLINE" },
    ],
  },
  {
    id: "s3",
    name: "Cà Phê Muối Chú Long",
    owner: "Lê Văn Hùng",
    phone: "0905 999 888",
    address: "88 Trần Phú, Ba Đình, Hà Nội",
    tableCount: 12,
    licenseKey: "A2-GROWTH-31AA0",
    plan: "GROWTH",
    status: "EXPIRING_SOON",
    activatedAt: "30/08/2026",
    expiresAt: "30/09/2026",
    daysLeft: 2,
    pingMs: 22,
    activeDevices: 3,
    configVer: "v1.0.0",
    businessType: "COFFEE_SHOP",
    lastSync: "2 phút trước",
    modules: [AppModule.CORE_POS, AppModule.MODULE_QR_ORDER, AppModule.MODULE_KDS],
    terminals: [
      { id: "term-301", name: "POS Thu Ngân Quầy Bar", role: "POS_CASHIER", ipAddress: "192.168.2.10", appVersion: "v1.0.0", lastSync: "2 phút trước", status: "ONLINE" },
      { id: "term-302", name: "KDS Màn Hình Pha Chế", role: "BAR_KDS", ipAddress: "192.168.2.11", appVersion: "v1.0.0", lastSync: "3 phút trước", status: "ONLINE" },
      { id: "term-303", name: "Tablet Phục Vụ Sân Vườn", role: "TABLET_WAITER", ipAddress: "192.168.2.14", appVersion: "v1.0.0", lastSync: "12 phút trước", status: "ONLINE" },
    ],
  },
  {
    id: "s4",
    name: "Lẩu Nướng Phố Cổ",
    owner: "Vũ Hải Đăng",
    phone: "0934 555 777",
    address: "12 Hàng Buồm, Hoàn Kiếm, Hà Nội",
    tableCount: 25,
    licenseKey: "A2-PRO-EXPIRED",
    plan: "PRO",
    status: "EXPIRED",
    activatedAt: "10/08/2026",
    expiresAt: "10/09/2026",
    daysLeft: 0,
    pingMs: 0,
    activeDevices: 0,
    configVer: "v1.0.5",
    businessType: "BEER_GARDEN",
    lastSync: "19 ngày trước",
    modules: [
      AppModule.CORE_POS,
      AppModule.MODULE_KDS,
      AppModule.MODULE_ACCOUNTING,
      AppModule.MODULE_LANDING_PAGE,
    ],
    terminals: [
      { id: "term-401", name: "POS Thu Ngân Chính", role: "POS_CASHIER", ipAddress: "192.168.10.5", appVersion: "v1.0.5", lastSync: "19 ngày trước", status: "OFFLINE" },
    ],
  },
];

export const INITIAL_INVOICES: SoftwareInvoiceRecord[] = [
  {
    id: "inv-1",
    invoiceCode: "INV-2026-0045",
    storeId: "s1",
    storeName: "Phở Bò Nam Định - Chi nhánh 1",
    plan: "Gói Chuỗi Chuyên Nghiệp (PRO)",
    durationMonths: 6,
    subTotal: 3594000,
    discountAmount: 600000,
    finalAmount: 2994000,
    status: "PAID",
    paymentMethod: "VIETQR",
    createdAt: "20/09/2026",
    paidAt: "20/09/2026 14:30",
  },
  {
    id: "inv-2",
    invoiceCode: "INV-2026-0046",
    storeId: "s3",
    storeName: "Cà Phê Muối Chú Long",
    plan: "Gói Quán Vừa (GROWTH)",
    durationMonths: 3,
    subTotal: 1197000,
    discountAmount: 100000,
    finalAmount: 1097000,
    status: "PENDING",
    paymentMethod: "VIETQR",
    createdAt: "28/09/2026",
  },
  {
    id: "inv-3",
    invoiceCode: "INV-2026-0047",
    storeId: "s2",
    storeName: "Bún Chả Cầu Giấy (Quán Nhỏ)",
    plan: "Gói Quán Nhỏ Tiết Kiệm (STARTER)",
    durationMonths: 12,
    subTotal: 2388000,
    discountAmount: 400000,
    finalAmount: 1988000,
    status: "PAID",
    paymentMethod: "VIETQR",
    createdAt: "15/09/2026",
    paidAt: "15/09/2026 10:15",
  },
];

export const INITIAL_AUDIT_LOGS: SystemAuditLogRecord[] = [
  {
    id: "a1",
    action: "EXTEND_LICENSE",
    storeName: "Phở Bò Nam Định",
    actor: "Quản trị viên mẫu",
    actorRole: "SUPER_ADMIN",
    ipAddress: "Chưa ghi nhận",
    timestamp: "18:45 Hôm nay",
    details: "Gia hạn hợp đồng thuê 6 tháng. Cập nhật License Key A2-PRO-9F8A2B",
    status: "SUCCESS",
  },
  {
    id: "a2",
    action: "CONFIRM_INVOICE",
    storeName: "Bún Chả Cầu Giấy",
    actor: "Quản trị viên mẫu",
    actorRole: "SUPER_ADMIN",
    ipAddress: "Chưa ghi nhận",
    timestamp: "15:20 Hôm nay",
    details: "Xác nhận đã nhận 1.988.000đ qua VietQR. Mở khóa gói STARTER 12 tháng",
    status: "SUCCESS",
  },
  {
    id: "a3",
    action: "AUTH_LOGIN",
    storeName: "Nền tảng A2Order",
    actor: "Quản trị viên mẫu",
    actorRole: "SUPER_ADMIN",
    ipAddress: "Chưa ghi nhận",
    timestamp: "12:00 Hôm nay",
    details: "Đăng nhập Super Admin bảo mật 2 lớp qua Khóa phiên SaaS Admin",
    status: "SUCCESS",
  },
  {
    id: "a4",
    action: "CONFIG_CHANGE",
    storeName: "Phở Bò Nam Định",
    actor: "Chủ quán mẫu",
    actorRole: "STORE_OWNER",
    ipAddress: "Chưa ghi nhận",
    timestamp: "11:30 Hôm nay",
    details: "Chủ quán xuất bản cấu hình thực đơn v1.0.3",
    status: "SUCCESS",
  },
];
